# -*- coding: utf-8 -*-
"""atmstumilator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1N5S0GdBmZHqy-RDYCw_r3EnMi9rKoU2i
"""

class ATM:
    def __init__(self, account_balance):
        self.account_balance = account_balance

    def check_balance(self):
        return self.account_balance

    def deposit(self, amount):
        if amount > 0:
            self.account_balance += amount
            return f"Deposited ${amount}. New balance: ${self.account_balance}"
        else:
            return "Invalid amount for deposit."

    def withdraw(self, amount):
        if amount > 0 and amount <= self.account_balance:
            self.account_balance -= amount
            return f"Withdrew ${amount}. New balance: ${self.account_balance}"
        else:
            return "Insufficient funds or invalid withdrawal amount."

def main():
    account_balance = 1000  # Initial account balance
    atm = ATM(account_balance)

    while True:
        print("\nATM Menu:")
        print("1. Check Balance")
        print("2. Deposit")
        print("3. Withdraw")
        print("4. Exit")

        choice = input("Enter your choice (1/2/3/4): ")

        if choice == '1':
            print(f"Your account balance is ${atm.check_balance()}")

        elif choice == '2':
            amount = float(input("Enter the deposit amount: $"))
            print(atm.deposit(amount))

        elif choice == '3':
            amount = float(input("Enter the withdrawal amount: $"))
            print(atm.withdraw(amount))

        elif choice == '4':
            print("Thank you for using this ATM. Goodbye!")
            break

        else:
            print("Invalid choice. Please enter 1, 2, 3, or 4.")

if __name__ == "__main__":
    main()