# -*- coding: utf-8 -*-
"""currency_converter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r-sM_mR3ApVFKQxZIhQ7p1SUhf0DlbF3
"""

import requests

# Define the base currency and the target currency
base_currency = "USD"
target_currency = "EUR"

# Set your API key here
api_key = "YOUR_API_KEY"

# Fetch the latest exchange rates from the API
url = f"https://open.er-api.com/v6/latest/{base_currency}/{api_key}"
response = requests.get(url)
data = response.json()

# Check if the API request was successful
if response.status_code == 200:
    exchange_rates = data["rates"]
    if target_currency in exchange_rates:
        # Get the exchange rate for the target currency
        rate = exchange_rates[target_currency]

        # Input the amount you want to convert
        amount = float(input(f"Enter the amount in {base_currency}: "))

        # Perform the currency conversion
        converted_amount = amount * rate

        print(f"{amount} {base_currency} is equal to {converted_amount} {target_currency}")
    else:
        print(f"Exchange rate for {target_currency} not available.")
else:
    print("Failed to fetch exchange rates. Please check your API key and try again.")