# -*- coding: utf-8 -*-
"""music_playlist.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18R_7OYqwDy95qe4fAvfmnsKrbSwQnIES
"""

import os
import pygame

# Initialize the pygame mixer
pygame.mixer.init(frequency=44100, size=-16, channels=2, buffer=4096)

# Function to add music to a playlist
def add_to_playlist(playlist, music_dir):
    for root, _, files in os.walk(music_dir):
        for file in files:
            if file.endswith(".mp3"):
                playlist.append(os.path.join(root, file))
    return playlist

# Function to display the playlist
def display_playlist(playlist):
    print("Playlist:")
    for i, song in enumerate(playlist, 1):
        print(f"{i}. {os.path.basename(song)}")

# Function to play music
def play_music(playlist, track_number):
    if 1 <= track_number <= len(playlist):
        pygame.mixer.music.load(playlist[track_number - 1])
        pygame.mixer.music.play()
        print(f"Playing: {os.path.basename(playlist[track_number - 1])}")
    else:
        print("Invalid track number.")

# Function to stop music
def stop_music():
    pygame.mixer.music.stop()
    print("Music stopped.")

# Main program loop
playlist = []
music_directory = "path/to/your/music/folder"  # Replace with your music directory path

if not os.path.exists(music_directory):
    print("Music directory not found. Please specify a valid directory path.")
else:
    playlist = add_to_playlist(playlist, music_directory)

while True:
    print("\nOptions:")
    print("1. Display Playlist")
    print("2. Play Music")
    print("3. Stop Music")
    print("4. Quit")

    choice = input("Enter your choice (1/2/3/4): ")

    if choice == '1':
        display_playlist(playlist)

    elif choice == '2':
        display_playlist(playlist)
        track_number = int(input("Enter the track number to play: "))
        play_music(playlist, track_number)

    elif choice == '3':
        stop_music()

    elif choice == '4':
        print("Thank you for using the music player. Goodbye!")
        pygame.mixer.quit()
        break

    else:
        print("Invalid choice. Please enter 1, 2, 3, or 4.")