# -*- coding: utf-8 -*-
"""randompass_generate.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Id7arVqrYQEIYcy9d9W4V2I39x4k2R1H
"""

import secrets
import string

def generate_password(length):
    characters = string.ascii_letters + string.digits + string.punctuation
    password = ''.join(secrets.choice(characters) for _ in range(length))
    return password

if __name__ == "__main__":
    try:
        password_length = int(input("Enter the length of the password: "))
        if password_length > 0:
            password = generate_password(password_length)
            print(f"Generated Password: {password}")
        else:
            print("Please enter a valid password length (greater than 0).")
    except ValueError:
        print("Invalid input. Please enter a valid number for password length.")