# -*- coding: utf-8 -*-
"""rocksizzors_game.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ns0pSj-w6zpKy1FeGuqVGcSvUS4n-hQs
"""

import random

def get_computer_choice():
    choices = ["rock", "paper", "scissors"]
    return random.choice(choices)

def determine_winner(user_choice, computer_choice):
    if user_choice == computer_choice:
        return "It's a tie!"
    if user_choice == "rock":
        if computer_choice == "scissors":
            return "You win!"
        else:
            return "Computer wins!"
    elif user_choice == "paper":
        if computer_choice == "rock":
            return "You win!"
        else:
            return "Computer wins!"
    elif user_choice == "scissors":
        if computer_choice == "paper":
            return "You win!"
        else:
            return "Computer wins!"

while True:
    user_choice = input("Rock, Paper, or Scissors? (Enter 'quit' to end): ").lower()

    if user_choice == "quit":
        break
    elif user_choice not in ["rock", "paper", "scissors"]:
        print("Invalid choice. Please choose from 'rock', 'paper', or 'scissors'.")
    else:
        computer_choice = get_computer_choice()
        print(f"Computer chooses {computer_choice}")
        result = determine_winner(user_choice, computer_choice)
        print(result)