# -*- coding: utf-8 -*-
"""temp_converter.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xsbr8nlkm5ThWbFaPeeGwQYkMKkqM27T
"""

def fahrenheit_to_celsius(fahrenheit):
    celsius = (fahrenheit - 32) * 5/9
    return celsius

def celsius_to_fahrenheit(celsius):
    fahrenheit = (celsius * 9/5) + 32
    return fahrenheit

while True:
    print("Options:")
    print("Enter '1' to convert Fahrenheit to Celsius")
    print("Enter '2' to convert Celsius to Fahrenheit")
    print("Enter '3' to quit")

    choice = input("Enter your choice: ")

    if choice == '3':
        break
    elif choice in ('1', '2'):
        try:
            temperature = float(input("Enter the temperature: "))
            if choice == '1':
                result = fahrenheit_to_celsius(temperature)
                print(f"{temperature}°F is equal to {result:.2f}°C")
            else:
                result = celsius_to_fahrenheit(temperature)
                print(f"{temperature}°C is equal to {result:.2f}°F")
        except ValueError:
            print("Invalid input. Please enter a valid number.")
    else:
        print("Invalid choice. Please enter 1, 2, or 3.")

