# -*- coding: utf-8 -*-
"""todolist_app.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FAJpddSRsA9G1TXSRkBuOFlM5O9Nu7u7
"""

# Create an empty to-do list
todo_list = []

# Function to add a task to the list
def add_task(task):
    todo_list.append(task)
    print(f"Task '{task}' added to the to-do list.")

# Function to view the to-do list
def view_list():
    if not todo_list:
        print("Your to-do list is empty.")
    else:
        print("To-Do List:")
        for i, task in enumerate(todo_list, 1):
            print(f"{i}. {task}")

# Function to mark a task as complete
def mark_complete(task_index):
    if 1 <= task_index <= len(todo_list):
        print(f"Task '{todo_list[task_index - 1]}' marked as complete.")
        del todo_list[task_index - 1]
    else:
        print("Invalid task index.")

# Function to remove a task from the list
def remove_task(task_index):
    if 1 <= task_index <= len(todo_list):
        print(f"Task '{todo_list[task_index - 1]}' removed from the to-do list.")
        del todo_list[task_index - 1]
    else:
        print("Invalid task index.")

# Main program loop
while True:
    print("\nOptions:")
    print("1. Add a task")
    print("2. View the to-do list")
    print("3. Mark a task as complete")
    print("4. Remove a task from the list")
    print("5. Quit")

    choice = input("Enter your choice (1/2/3/4/5): ")

    if choice == '1':
        task = input("Enter the task: ")
        add_task(task)

    elif choice == '2':
        view_list()

    elif choice == '3':
        view_list()
        task_index = int(input("Enter the task number to mark as complete: "))
        mark_complete(task_index)

    elif choice == '4':
        view_list()
        task_index = int(input("Enter the task number to remove from the list: "))
        remove_task(task_index)

    elif choice == '5':
        print("Thank you for using the to-do list. Goodbye!")
        break

    else:
        print("Invalid choice. Please enter 1, 2, 3, 4, or 5.")